language: generic
sudo: false
addons:
  apt:
    packages:
    - git
    - build-essential
    - curl
script:
- BUILD_HOME="$TRAVIS_BUILD_DIR" ./install.sh
- BUILD_HOME="$TRAVIS_BUILD_DIR" DEPLOY_TO="$TRAVIS_BUILD_DIR/deploy/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH" ./build.sh
deploy:
  skip_cleanup: true
  provider: s3
  bucket: aptible-cadvisor
  acl: private
  local_dir: deploy
  access_key_id:
    secure: mH5GfuMq0i4rqO9bIDA7+tAdmEF3nGJ/keshfUWZrVDCOAm9istfQci4QJvAjRkh6ZcNmRv9GlNzznIWwVxNzw/MQyzlqet9DPOHZrK8uXpwvxdqN1BIVK8VElGjkw0aq3Z+1sT1qMotDlIUAF+NS+Mm0xN6j2jqUKayZdrZtpk0muyORhhNeaMQwram0abN1nNFgzkiuAKcWEwtKDzIh3b/tusMjbwMGabsZWM4vjSpwhvNLifxeAL5HTYqGgiMHIONZXU61OBQXpu+UtpemQk6CkFrUiJ6Z97IsamMWZnCAb4AfUYZ8dM4UFExKKxblUasomxrQl/anE8HPKS0iO3lNMkkqzzKchZ/YWL+V7vSoLBfDgEREYWSTh5npRrahkaWuq/Biwjem0U6FVpU+DAU/Y3C7dk86vCmUJZvY1a9hy6yDoC4hqoWLVhfENkD/lUfEt0ENKmytCfq6rQJWz1mPIIO+VKgRI7ilH6WWctqjn7h9RKYbncaRXhQGfUy+qlRxiVksL8sxct+/EBVzIreZVaD4C7My8uuUfig2FKytfu7UfeHYbbAWsGtzhJZhjzNoM8iPpNz7tEie8SgJNcxMUS/zIpPR2FQEbAkoDuMfdNxg8aKN52buGqe4w5p2mfKLf+cvGT8Lu993S2iG8maZLhaDoUnfPVt+JPQy/E=
  secret_access_key:
    secure: X4uYDow9yFD2I3Krp0E6lwl9voiyQ852wpiJRKwwHVtauHkUDizl4/DMovOA8UBt3oijHrky4e5tC36sQcRRReQ40dYArXtLmqxV2l9kuodZsa2HCCVAWY9OkIDJmeuPLHmTA+oxqxwmEnOgJr6BN8ez9yT0KtU2eoXs5F4/wqH60lw9RbMksp88diAikmGQmrQcdFeT83XMoHE6PY3wvOO1OnNULlh3GJb6WK49ljbcndj5keCSuQheXTgXUzCB1xzsLV5yA/O9Tbz+D+NGnRslW/6Hq/0Ah2NWfqfUeSLWFvIKwuVSzjxLx/9Ktcqcy0HdHQjngB9lWBQJOa/3/VdKR7B3jcozuVF7myuBDvu5Y5klWKm0sU7uabhx4au8lh5kz4i9zbk5V9hrJKzc2ZVj5H1lOTDURSdb1EAf5nGVpgbcBGBBrVFb6DmOEFxoGkcK2NN84Yb8CC0duW+0EwTi0h/jpL2Tjhikxe38qyvbbBUF9QL/ut0XlnVWWn9z3GmwXv5rljARC4urCmJ5mbtOKgz9JFU3pxcOoX1kQlOP+8Dvkd5xgQVYcIKz5a+dQ9n0Z2tze4j9iW5UJCesi4bAIzGblZ+z58FbXfag8K2bDndvHwYM2I8Z+FTbGA7NeJPC4f4NlGDKxIjE/+WpSbeOZPeefNVAQVITJKdEOj4=
  on:
    repo: aptible/cadvisor-factory
    all_branches: true
